export const Attribute = {
  Comments: "Comments",
  Contact: "Contact",
  CreationDate: "Creation Date",
  Domain: "Domain",
  EndOfSaleDate: "End of Sale Date",
  EndOfLifeDate: "End of Life Date",
  Family: "Family",
  Id: "ID",
  Interface: "Interface",
  Ip: "IP",
  LastChangeDate: "Last Change Date",
  Location: "Location",
  Mac: "MAC",
  Module: "Module",
  Name: "Name",
  NetworkClass: "Network Class",
  SerialNumber: "Serial Number",
  SoftwareLevel: "Software Level",
  SoftwareVersion: "Software Version",
  Status: "Status",
  Type: "Type",
  VirtualName: "Virtual Name",
  Vrf: "VRF",
} as const

export type AttributeName = keyof typeof Attribute
