export const QUERIES = {
  DEVICE_SEARCH_LIST: "device-search-list",
  DEVICE_TYPE_LIST: "device-type-list",
  DEVICE_DETAIL: "device-detail",
  DEVICE_CONFIGS: "device-configs",
  DEVICE_CONFIG: "device-config",
  DEVICE_INTERFACES: "device-interfaces",
  DEVICE_MODULES: "device-modules",
  DEVICE_TASKS: "device-tasks",
  DEVICE_DIAGNOSTIC: "device-diagnostic",
  DEVICE_COMPLIANCE: "device-compliance",
  DEVICE_REMOVE: "device-remove",
  DEVICE_DISABLE: "device-disable",
  DEVICE_ENABLE: "device-enable",
}
